**1.**

In [1]:
import numpy as np

In [10]:
# formado apenas por 1's
arr = np.ones(8)
print(arr)

# aleatórios dentre 0 a 9
arr2 = np.random.randint(0, 9, 8)
print(arr2)

# soma dos dois arrays
arr3 = arr + arr2
print(arr3)

# soma de todos os elementos do array resultante
soma_total = arr3.sum()
print("Soma total:", soma_total)

# reshape condicional
if soma_total >= 40:
    # mais linhas do que colunas -> 4 linhas x 2 colunas
    matriz = arr3.reshape(4, 2)
else:
    # mais colunas do que linhas -> 2 linhas x 4 colunas
    matriz = arr3.reshape(2, 4)

print(matriz)

[1. 1. 1. 1. 1. 1. 1. 1.]
[1 5 5 3 4 8 6 5]
[2. 6. 6. 4. 5. 9. 7. 6.]
Soma total: 45.0
[[2. 6.]
 [6. 4.]
 [5. 9.]
 [7. 6.]]


**2.**

In [22]:
# matriz 2x2
matriz = np.zeros([2,2])

# adiciona um 1 em uma posição aleatória
linha = np.random.randint(0, matriz.shape[0])
coluna = np.random.randint(0, matriz.shape[1])

matriz[linha, coluna] = 1

# campo minado
perdeu = False
pos = set()  # guardar as casas que o rapaizinho já colocou
total = matriz.size - 1

for i in range(3):
    print(f"Jogada {i+1} de 3")

    while True:
        linha2 = int(input("Escolha uma linha (0 ou 1): "))
        coluna2 = int(input("Escolha uma coluna (0 ou 1): "))

        if (linha2, coluna2) in pos:
            print("Você já jogou nessa posição! Escolha outra.")
        else:
            break

    if matriz[linha2, coluna2] == 1:
        print("Game Over! :( Try Again!")
        perdeu = True
        break

    pos.add((linha2, coluna2))

if not perdeu and len(pos) == total:
    print("Congratulations! You beat the game! :)")

print(matriz)

Jogada 1 de 3
Escolha uma linha (0 ou 1): 0
Escolha uma coluna (0 ou 1): 0
Game Over! :( Try Again!
[[1. 0.]
 [0. 0.]]


**3.**

In [23]:
# cria uma matriz de tamanho qualquer
matriz = np.zeros([4, 3])
print(matriz)

# extrai linhas e colunas
linhas, colunas = matriz.shape
print("Linhas:", linhas)
print("Colunas:", colunas)

# multiplica
total = linhas * colunas
print("Total de elementos:", total)

# par ou ímpar
if total % 2 == 0:
    print("A matriz pode virar um vetor unidimensional com número PAR de elementos.")
else:
    print("A matriz pode virar um vetor unidimensional com número ÍMPAR de elementos.")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Linhas: 4
Colunas: 3
Total de elementos: 12
A matriz pode virar um vetor unidimensional com número PAR de elementos.


**4.**

In [24]:
np.random.seed(10)
matriz = np.random.randint(1, 51, size=(4, 4))
print("Matriz:")
print(matriz)

# média de cada linha e cada coluna
media_linhas = matriz.mean(axis=1)
media_colunas = matriz.mean(axis=0)
print("Média de cada linha:", media_linhas)
print("Média de cada coluna:", media_colunas)

# maior valor entre as médias
maior_media_linha = media_linhas.max()
maior_media_coluna = media_colunas.max()
print("Maior média entre as linhas:", maior_media_linha)
print("Maior média entre as colunas:", maior_media_coluna)

# quantidade de aparições de cada número '-'
valores, contagens = np.unique(matriz, return_counts=True)
print("Valores:", valores)
print("Contagens:", contagens)

# números que aparecem exatamente 2 vezes
valores_2x = valores[contagens == 2]
print("Números que aparecem 2 vezes:", valores_2x)

Matriz:
[[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]
Média de cada linha: [16.   33.75 34.5  23.75]
Média de cada coluna: [29.75 24.25 33.75 20.25]
Maior média entre as linhas: 34.5
Maior média entre as colunas: 33.75
Valores: [ 1  9 10 16 26 29 30 37 41 43 49 50]
Contagens: [2 1 2 1 1 1 2 1 1 1 1 2]
Números que aparecem 2 vezes: [ 1 10 30 50]


**5.**

In [25]:
# matriz 3x3 de zeros
zeros = np.zeros((3, 3))
print("Zeros:")
print(zeros)

# matriz 3x3 de uns
uns = np.ones((3, 3))
print("Uns:")
print(uns)

# soma elemento a elemento
soma = zeros + uns
print("Soma:")
print(soma)

# multiplica por um escalar (escolhi 5)
escalar = 5
resultado = soma * escalar
print("Resultado (soma * escalar):")
print(resultado)

# reshape para vetor 1D de 9 elementos
vetor = resultado.reshape(9)
print("Vetor 1D:")
print(vetor)

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Uns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Soma:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Resultado (soma * escalar):
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Vetor 1D:
[5. 5. 5. 5. 5. 5. 5. 5. 5.]


**6.**

In [26]:
# números de 10 a 30, de 2 em 2
arr = np.arange(10, 31, 2)
print("Array:", arr)

# maior valor e seu índice
maior = arr.max()
indice_maior = arr.argmax()
print("Maior valor:", maior, "| índice:", indice_maior)

# menor valor e seu índice
menor = arr.min()
indice_menor = arr.argmin()
print("Menor valor:", menor, "| índice:", indice_menor)

# soma de todos os elementos
soma = arr.sum()
print("Soma:", soma)

Array: [10 12 14 16 18 20 22 24 26 28 30]
Maior valor: 30 | índice: 10
Menor valor: 10 | índice: 0
Soma: 220


**7.**

In [27]:
np.random.seed(7)

# dois arrays de tamanho 5, números entre 1 e 10
arr1 = np.random.randint(1, 11, 5)
arr2 = np.random.randint(1, 11, 5)
print("arr1:", arr1)
print("arr2:", arr2)

# concatena os dois em um terceiro
arr3 = np.concatenate((arr1, arr2))
print("arr3:", arr3)

# transforma em matriz 2x5
matriz = arr3.reshape(2, 5)
print("Matriz:")
print(matriz)

arr1: [ 5 10  7  4  4]
arr2: [ 8  8 10  8  9]
arr3: [ 5 10  7  4  4  8  8 10  8  9]
Matriz:
[[ 5 10  7  4  4]
 [ 8  8 10  8  9]]
